name=RumiCar
version=0.1.0
author=RumiCar-group
maintainer=RumiCar-group
sentence=Library for controlling the RumiCar platform.
paragraph=Provides setup and control functions for steering and drive motors, and initializes VL53L0X sensors.
category=Device Control
url=https://github.com/RumiCar-group/RumiCar-lib
architectures=*
depends=VL53L0X
